### ISSUE TITLE
Vehicle ID has changed

### ISSUE THREAD

**Issue by abubakarm94** [tals/uber.py#8]
It seems like Uber has changed the vehicle id for UberX. As of this message I believe the working vehicle id is 2008 for UberX

**Comment by tals** [comment]
Why not use uber's official API?

**Comment by abubakarm94** [comment]
Uber doesn't have a python official API

On Friday, December 18, 2015, Tal Sh <notifications@github.com> wrote:

> Reopened #8 <https://github.com/tals/uber.py/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tals/uber.py/issues/8#event-495504484>.
>


-- 
*Abubakar Mohammed*
Villanova University 2016 | College of Liberal Arts & Sciences
Bachelor of Sciences, Computer Science
Computing Sciences, Lab Consultant, Mendel Hall

**Comment by tals** [comment]
https://github.com/uber/Python-Sample-Application/

**Comment by abubakarm94** [comment]
Great!! Thanks

On Friday, December 18, 2015, Tal Sh <notifications@github.com> wrote:

> https://github.com/uber/Python-Sample-Application/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tals/uber.py/issues/8#issuecomment-165868234>.
>


-- 
*Abubakar Mohammed*
Villanova University 2016 | College of Liberal Arts & Sciences
Bachelor of Sciences, Computer Science
Computing Sciences, Lab Consultant, Mendel Hall
